baseURL = "https://yoursite.com"
languageCode = "en-us"
title = "your titile"
theme = "Light"

# It's example for section page.
# If you will creat your new section,
# you need castomize.
[[menu.main]]
	name = "Documents"
	identifier = "documents"
	category = "docs"
	url = "/documents/"
	weight = 1


[[menu.main]]
	name = "About"
	identifier = "about"
	category = "about"
	url = "/about/"
	weight = 2

[[menu.main]]
	name = "Diary"
	identifier = "diary"
	category = "diary"
	url = "/diary/"
	weight = 3


[params]
	paginate = 10
# Social accounts. Link to these accounts are displayed in the header and
# footer
	twitter = "Your Twitter username"
	facebook = "Your Facebook username"
#	instagram = "Your Instagram username"
#	googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
	github = "Your GitHub username"
#	gitlab = "Your GitLab username"
#	npm = "Your npm username"
#	codepen = "Your CodePen username"
#	dribbble = "Your Dribbble username"
#	fivehundredpx = "Your 500px username" # 500px
#	flickr = "Your Flickr username"
#	pinterest = "Your Pinterest username"
#	tumblr = "Your Tumblr username"
#	vimeo = "Your Vimeo username"
#	youtube = "Your YouTube username"
	linkedin = "Your LinkedIn username"
# Disqus shortname
	disqus = ""
# Google Analytics API key.
#	ga_api_key = "Your Google Analytics tracking id"
#	author = "Your Name"
#	authorwebsite = "example.com"
#	avatar = "/path/to/avatar"
#	contact = "Your contact link (ex. mailto:foo@example.com)"
#	bio = "Your short bio"
# Short subtitle/tagline. This is displayed in the header.
#	subtitle = "Short subtitle"
# Logo image. This is displayed ogp image.
#	logo = "/path/to/logo"
#	favicon = "/path/to/favicon"
