baseURL = "https://xcd0.github.io/"
languageCode = "ja-jp"
title = "xcd0.github.io"
#theme = "code-editor"
theme = "learn"
[params]
    author = "xcd0"
    locale = "ja-JP"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.
