baseURL = "https://xcd0.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "code-editor"
[params]
    author = "xcd0"
    locale = "ja-JP"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.
