baseURL = "https://xcd0.github.io/"
languageCode = "ja-jp"
title = "Top: light"
theme = "github-project-landing-page"

[params]
    description = "Next editor application."
    project_url = "https://github.com/xcd0/light"
    project_documentation = "https://xcd0.github.io/docs"

    github_project_name = "light"
    github_user_name = "light"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

    author = "xcd0"
    author_url = "http://github.com/xcd0"
    locale = "ja-JP"

